FROM node:14.7.0-alpine as build-env
COPY . /app
WORKDIR /app
RUN yarn install
RUN yarn run build

FROM nginx:1.19.2-alpine as final
RUN mkdir /var/www
RUN chmod 777 /var/www
COPY --from=build-env /app/public/ /var/www
COPY ./nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
